import { Toy } from "./schema-type";

type Toys = Toy[];

export const dataToys: Toys = [
  {
    id: 1,
    sku: "T001",
    name: "Rocket Shooter",
    slug: "rocket-shooter",
    category: {
      id: 1,
      name: "Outdoor Toys",
    },
    brand: "KidX",
    price: 75000,
    ageRange: "5-10",
    image: "https://example.com/toys/rocket_shooter.png",
    description: "Mainan roket busa untuk aktivitas outdoor.",
    createdAt: new Date("2025-01-01T10:00:00Z"),
    updatedAt: null,
  },
  {
    id: "T002",
    name: "Building Blocks Set",
    slug: "building-blocks-set",
    category: {
      id: 2,
      name: "Educational Toys",
    },
    brand: "EduFun",
    price: 125000,
    ageRange: "3-8",
    image: "https://example.com/toys/building_blocks.png",
    description: "Set blok bangunan berwarna-warni untuk kreativitas.",
    createdAt: new Date("2025-01-02T09:30:00Z"),
    updatedAt: null,
  },
  {
    id: "T003",
    name: "Remote Control Car",
    slug: "remote-control-car",
    category: {
      id: 3,
      name: "Electronic Toys",
    },
    brand: "TechToy",
    price: 250000,
    ageRange: "6-12",
    image: "https://example.com/toys/rc_car.png",
    description: "Mobil RC dengan kecepatan tinggi dan lampu LED.",
    createdAt: new Date("2025-01-03T11:15:00Z"),
    updatedAt: null,
  },
  {
    id: "T004",
    name: "Doctor Playset",
    slug: "doctor-playset",
    category: {
      id: 4,
      name: "Role Play",
    },
    brand: "PlayLearn",
    price: 95000,
    ageRange: "4-7",
    image: "https://example.com/toys/doctor_set.png",
    description: "Set dokter lengkap dengan stetoskop dan alat medis mainan.",
    createdAt: new Date("2025-01-04T08:45:00Z"),
    updatedAt: null,
  },
  {
    id: "T005",
    name: "Water Gun",
    slug: "water-gun",
    category: {
      id: 1,
      name: "Outdoor Toys",
    },
    brand: "AquaFun",
    price: 55000,
    ageRange: "5-10",
    image: "https://example.com/toys/water_gun.png",
    description: "Pistol air dengan kapasitas besar untuk bermain outdoor.",
    createdAt: new Date("2025-01-05T13:20:00Z"),
    updatedAt: null,
  },
  {
    id: "T006",
    name: "Magnetic Drawing Board",
    slug: "magnetic-drawing-board",
    category: {
      id: 2,
      name: "Educational Toys",
    },
    brand: "ArtMagic",
    price: 65000,
    ageRange: "3-6",
    image: "https://example.com/toys/drawing_board.png",
    description:
      "Papan gambar magnetik yang bisa dihapus dan digunakan kembali.",
    createdAt: new Date("2025-01-06T10:10:00Z"),
    updatedAt: null,
  },
  {
    id: "T007",
    name: "Robot Dinosaur",
    slug: "robot-dinosaur",
    category: {
      id: 3,
      name: "Electronic Toys",
    },
    brand: "RoboKid",
    price: 320000,
    ageRange: "5-10",
    image: "https://example.com/toys/robot_dino.png",
    description:
      "Dinosaurus robotik yang bisa berjalan dan mengeluarkan suara.",
    createdAt: new Date("2025-01-07T14:50:00Z"),
    updatedAt: null,
  },
  {
    id: "T008",
    name: "Kitchen Set",
    slug: "kitchen-set",
    category: {
      id: 4,
      name: "Role Play",
    },
    brand: "PlayHouse",
    price: 180000,
    ageRange: "3-8",
    image: "https://example.com/toys/kitchen_set.png",
    description: "Set dapur mainan lengkap dengan peralatan masak.",
    createdAt: new Date("2025-01-08T09:00:00Z"),
    updatedAt: null,
  },
  {
    id: "T009",
    name: "Flying Disc",
    slug: "flying-disc",
    category: {
      id: 1,
      name: "Outdoor Toys",
    },
    brand: "SkyPlay",
    price: 35000,
    ageRange: "6-12",
    image: "https://example.com/toys/flying_disc.png",
    description: "Frisbee warna-warni untuk bermain di taman.",
    createdAt: new Date("2025-01-09T11:30:00Z"),
    updatedAt: null,
  },
  {
    id: "T010",
    name: "Alphabet Puzzle",
    slug: "alphabet-puzzle",
    category: {
      id: 2,
      name: "Educational Toys",
    },
    brand: "LearnSmart",
    price: 75000,
    ageRange: "2-5",
    image: "https://example.com/toys/alphabet_puzzle.png",
    description: "Puzzle kayu dengan huruf alfabet untuk belajar membaca.",
    createdAt: new Date("2025-01-10T08:15:00Z"),
    updatedAt: null,
  },
];
