export const toys = [
  {
    sku: "T001",
    name: "Rocket Shooter",
    slug: "rocket-shooter",
    categoryId: 1,
    brand: "KidX",
    price: 75000,
    ageRange: "5-10",
    image: "https://m.media-amazon.com/images/I/71ApaCT7FUL.jpg",
    description: "Foam rocket toys for outdoor activities.",
  },
  {
    sku: "T002",
    name: "Building Blocks Set",
    slug: "building-blocks-set",
    categoryId: 2,
    brand: "EduFun",
    price: 125000,
    ageRange: "3-8",
    image: "https://m.media-amazon.com/images/I/71CuhmLzNaL.jpg",
    description: "Colorful building block set for creativity.",
  },
  {
    sku: "T003",
    name: "Remote Control Car",
    slug: "remote-control-car",
    categoryId: 3,
    brand: "TechToy",
    price: 250000,
    ageRange: "6-12",
    image: "https://m.media-amazon.com/images/I/71YRfYWtXbL.jpg",
    description: "Remote control car with high speed and LED lights.",
  },
  {
    sku: "T004",
    name: "Dollhouse",
    slug: "dollhouse",
    categoryId: 4,
    brand: "PlayHome",
    price: 300000,
    ageRange: "4-10",
    image: "https://m.media-amazon.com/images/I/81Z4G+8bJDL.jpg",
    description: "Wooden dollhouse with furniture and accessories.",
  },
  {
    sku: "T005",
    name: "Puzzle Game",
    slug: "puzzle-game",
    categoryId: 2,
    brand: "BrainyKids",
    price: 50000,
    ageRange: "3-7",
    image: "https://m.media-amazon.com/images/I/71VZ6Y0bXoL.jpg",
    description: "Colorful puzzle game to enhance problem-solving skills.",
  },
];

export const categories = [
  { id: 1, name: "Outdoor Toys", slug: "outdoor-toys" },
  { id: 2, name: "Educational Toys", slug: "educational-toys" },
  { id: 3, name: "Electronic Toys", slug: "electronic-toys" },
  { id: 4, name: "Dolls & Action Figures", slug: "dolls-action-figures" },
  { id: 5, name: "Vehicles & Remote Control", slug: "vehicles-remote-control" },
  { id: 6, name: "Building & Construction", slug: "building-construction" },
  { id: 7, name: "Arts & Crafts", slug: "arts-crafts" },
  { id: 8, name: "Plush Toys", slug: "plush-toys" },
  { id: 9, name: "Games & Puzzles", slug: "games-puzzles" },
  { id: 10, name: "Infant & Toddler Toys", slug: "infant-toddler-toys" },
];
