export const toys = [
  {
    sku: "T001",
    name: "Rocket Shooter",
    slug: "rocket-shooter",
    categorySlug: "outdoor-toys",
    brand: "KidX",
    price: 75000,
    ageRange: "5-10",
    imageUrl: "https://m.media-amazon.com/images/I/71ApaCT7FUL.jpg",
    description: "Foam rocket toys for outdoor activities.",
  },
  {
    sku: "T002",
    name: "Building Blocks Set",
    slug: "building-blocks-set",
    categorySlug: "educational-toys",
    brand: "EduFun",
    price: 125000,
    ageRange: "3-8",
    imageUrl: "https://m.media-amazon.com/images/I/71CuhmLzNaL.jpg",
    description: "Colorful building block set for creativity.",
  },
  {
    sku: "T003",
    name: "Remote Control Car",
    slug: "remote-control-car",
    categorySlug: "vehicles-remote-control",
    brand: "TechToy",
    price: 250000,
    ageRange: "6-12",
    imageUrl: "https://m.media-amazon.com/images/I/71YRfYWtXbL.jpg",
    description: "Remote control car with high speed and LED lights.",
  },
  {
    sku: "T004",
    name: "Dollhouse",
    slug: "dollhouse",
    categorySlug: "dolls-action-figures",
    brand: "PlayHome",
    price: 300000,
    ageRange: "4-10",
    imageUrl: "https://m.media-amazon.com/images/I/81Z4G+8bJDL.jpg",
    description: "Wooden dollhouse with furniture and accessories.",
  },
  {
    sku: "T005",
    name: "Puzzle Game",
    slug: "puzzle-game",
    categorySlug: "educational-toys",
    brand: "BrainyKids",
    price: 50000,
    ageRange: "3-7",
    imageUrl: "https://m.media-amazon.com/images/I/71VZ6Y0bXoL.jpg",
    description: "Colorful puzzle game to enhance problem-solving skills.",
  },
  {
    sku: "T006",
    name: "Action Figure Set",
    slug: "action-figure-set",
    categorySlug: "dolls-action-figures",
    brand: "HeroPlay",
    price: 150000,
    ageRange: "5-12",
    imageUrl: "https://m.media-amazon.com/images/I/81e+5b1gWDL.jpg",
    description: "Set of action figures with movable joints and accessories.",
  },
  {
    sku: "T007",
    name: "Remote Control Helicopter",
    slug: "remote-control-helicopter",
    categorySlug: "vehicles-remote-control",
    brand: "FlyHigh",
    price: 350000,
    ageRange: "8-14",
    imageUrl: "https://m.media-amazon.com/images/I/71j8e8q3yDL.jpg",
    description:
      "Remote control helicopter with stable flight and easy controls.",
  },
  {
    sku: "T008",
    name: "Art & Craft Kit",
    slug: "art-craft-kit",
    categorySlug: "arts-crafts",
    brand: "CreativeKids",
    price: 80000,
    ageRange: "4-10",
    imageUrl: "https://m.media-amazon.com/images/I/81Yk6b1gWDL.jpg",
    description:
      "Complete art and craft kit with various supplies for creativity.",
  },
  {
    sku: "T009",
    name: "Outdoor Explorer Set",
    slug: "outdoor-explorer-set",
    categorySlug: "outdoor-toys",
    brand: "AdventureKids",
    price: 90000,
    ageRange: "6-12",
    imageUrl: "https://m.media-amazon.com/images/I/71Z8e8q3yDL.jpg",
    description: "Explorer set with binoculars, compass, and magnifying glass.",
  },
  {
    sku: "T010",
    name: "Musical Instrument Set",
    slug: "musical-instrument-set",
    categorySlug: "arts-crafts",
    brand: "MusicFun",
    price: 110000,
    ageRange: "3-8",
    imageUrl: "https://m.media-amazon.com/images/I/71M8e8q3yDL.jpg",
    description:
      "Set of musical instruments including tambourine, maracas, and xylophone.",
  },
];

export const categories = [
  { name: "Outdoor Toys", slug: "outdoor-toys" },
  { name: "Educational Toys", slug: "educational-toys" },
  { name: "Electronic Toys", slug: "electronic-toys" },
  { name: "Dolls & Action Figures", slug: "dolls-action-figures" },
  { name: "Vehicles & Remote Control", slug: "vehicles-remote-control" },
  { name: "Arts & Crafts", slug: "arts-crafts" },
];
