export const toys = [
  {
    sku: "T001",
    name: "Rocket Shooter",
    slug: "rocket-shooter",
    categorySlug: "outdoor-toys",
    brandSlug: "techtoy",
    price: 75000,
    ageRange: "5-10",
    imageUrl: "https://m.media-amazon.com/images/I/71ApaCT7FUL.jpg",
    description: "Foam rocket toys for outdoor activities.",
  },
  {
    sku: "T002",
    name: "Building Blocks Set",
    slug: "building-blocks-set",
    categorySlug: "educational-toys",
    brandSlug: "playhome",
    price: 125000,
    ageRange: "3-8",
    imageUrl: "https://m.media-amazon.com/images/I/71CuhmLzNaL.jpg",
    description: "Colorful building block set for creativity.",
  },
  {
    sku: "T003",
    name: "Remote Control Car",
    slug: "remote-control-car",
    categorySlug: "vehicles-remote-control",
    brandSlug: "heroplay",
    price: 250000,
    ageRange: "6-12",
    imageUrl: "https://m.media-amazon.com/images/I/71YRfYWtXbL.jpg",
    description: "Remote control car with high speed and LED lights.",
  },
  {
    sku: "T004",
    name: "Dollhouse",
    slug: "dollhouse",
    categorySlug: "dolls-action-figures",
    brandSlug: "flyhigh",
    price: 300000,
    ageRange: "4-10",
    imageUrl: "https://m.media-amazon.com/images/I/81Z4G+8bJDL.jpg",
    description: "Wooden dollhouse with furniture and accessories.",
  },
  {
    sku: "T005",
    name: "Puzzle Game",
    slug: "puzzle-game",
    categorySlug: "educational-toys",
    brandSlug: "creativekids",
    price: 50000,
    ageRange: "3-7",
    imageUrl: "https://m.media-amazon.com/images/I/71VZ6Y0bXoL.jpg",
    description: "Colorful puzzle game to enhance problem-solving skills.",
  },
  {
    sku: "T006",
    name: "Action Figure Set",
    slug: "action-figure-set",
    categorySlug: "dolls-action-figures",
    brandSlug: "adventurekids",
    price: 150000,
    ageRange: "5-12",
    imageUrl: "https://m.media-amazon.com/images/I/81e+5b1gWDL.jpg",
    description: "Set of action figures with movable joints and accessories.",
  },
  {
    sku: "T007",
    name: "Remote Control Helicopter",
    slug: "remote-control-helicopter",
    categorySlug: "vehicles-remote-control",
    brandSlug: "musicfun",
    price: 350000,
    ageRange: "8-14",
    imageUrl: "https://m.media-amazon.com/images/I/71j8e8q3yDL.jpg",
    description:
      "Remote control helicopter with stable flight and easy controls.",
  },
  {
    sku: "T008",
    name: "Art & Craft Kit",
    slug: "art-craft-kit",
    categorySlug: "arts-crafts",
    brandSlug: "creativekids",
    price: 80000,
    ageRange: "4-10",
    imageUrl: "https://m.media-amazon.com/images/I/81Yk6b1gWDL.jpg",
    description:
      "Complete art and craft kit with various supplies for creativity.",
  },
  {
    sku: "T009",
    name: "Outdoor Explorer Set",
    slug: "outdoor-explorer-set",
    categorySlug: "outdoor-toys",
    brandSlug: "adventurekids",
    price: 90000,
    ageRange: "6-12",
    imageUrl: "https://m.media-amazon.com/images/I/71Z8e8q3yDL.jpg",
    description: "Explorer set with binoculars, compass, and magnifying glass.",
  },
  {
    sku: "T010",
    name: "Musical Instrument Set",
    slug: "musical-instrument-set",
    categorySlug: "arts-crafts",
    brandSlug: "musicfun",
    price: 110000,
    ageRange: "3-8",
    imageUrl: "https://m.media-amazon.com/images/I/71M8e8q3yDL.jpg",
    description:
      "Set of musical instruments including tambourine, maracas, and xylophone.",
  },
  {
    sku: "T011",
    name: "Statue Heron A - The Boy and the Heron",
    slug: "statue-heron-a-the-boy-and-the-heron",
    categorySlug: "statues",
    brandSlug: "bandai-namco",
    price: 120000,
    ageRange: "4-10",
    imageUrl:
      "https://p-bandai.com/files/seller-products/FSP0001951001/S23qSQN3sLkYMXWz0Z51.jpg?w=1440&h=1440",
    description: "A statue of the gray heron that appears in the movie.",
  },
  {
    sku: "L001",
    name: "LEGO City Fire Station",
    slug: "lego-city-fire-station",
    brandSlug: "lego",
    price: 899000,
    ageRange: "6-12",
    imageUrl:
      "https://www.lego.com/cdn/cs/set/assets/blt4b7f0c9e1a3e2c8c/60320.png",
    description:
      "A multi-level LEGO City Fire Station set featuring fire trucks, a helicopter, and firefighter minifigures.",
  },
  {
    sku: "L002",
    name: "LEGO Star Wars X-Wing Starfighter",
    slug: "lego-star-wars-x-wing-starfighter",
    categorySlug: "building-sets",
    brandSlug: "lego",
    price: 1099000,
    ageRange: "9-14",
    imageUrl:
      "https://www.lego.com/cdn/cs/set/assets/blt3b6c7a6f3b4a1e64/75301.png",
    description:
      "An iconic X-Wing Starfighter from Star Wars, complete with Luke Skywalker minifigure and opening wings.",
  },
  {
    sku: "L003",
    name: "LEGO Creator 3-in-1 Pirate Ship",
    slug: "lego-creator-3-in-1-pirate-ship",
    categorySlug: "building-sets",
    brandSlug: "lego",
    price: 1599000,
    ageRange: "9-16",
    imageUrl:
      "https://www.lego.com/cdn/cs/set/assets/blt2c45d7a1b7a38c9f/31109.png",
    description:
      "A versatile 3-in-1 LEGO Creator set that can be rebuilt into a pirate ship, skull island, or pirate inn.",
  },
  {
    sku: "L004",
    name: "LEGO Technic Bugatti Bolide",
    slug: "lego-technic-bugatti-bolide",
    categorySlug: "vehicles",
    brandSlug: "lego",
    price: 749000,
    ageRange: "9-16",
    imageUrl:
      "https://www.lego.com/cdn/cs/set/assets/blt5f1b7a92bfe91a2a/42151.png",
    description:
      "A detailed LEGO Technic model of the Bugatti Bolide, featuring realistic mechanics and sporty design.",
  },
];

export const categories = [
  { name: "Outdoor Toys", slug: "outdoor-toys" },
  { name: "Educational Toys", slug: "educational-toys" },
  { name: "Electronic Toys", slug: "electronic-toys" },
  { name: "Dolls & Action Figures", slug: "dolls-action-figures" },
  { name: "Vehicles & Remote Control", slug: "vehicles-remote-control" },
  { name: "Arts & Crafts", slug: "arts-crafts" },
  { name: "Statues", slug: "statues" },
  { name: "Building Sets", slug: "building-sets" },
  { name: "Vehicles", slug: "vehicles" },
];

export const brands = [
  {
    name: "TechToy",
    slug: "techtoy",
    logo: "https://example.com/logos/techtoy.png",
  },
  {
    name: "PlayHome",
    slug: "playhome",
    logo: "https://example.com/logos/playhome.png",
  },
  {
    name: "HeroPlay",
    slug: "heroplay",
    logo: "https://example.com/logos/heroplay.png",
  },
  {
    name: "FlyHigh",
    slug: "flyhigh",
    logo: "https://example.com/logos/flyhigh.png",
  },
  {
    name: "CreativeKids",
    slug: "creativekids",
    logo: "https://example.com/logos/creativekids.png",
  },
  {
    name: "AdventureKids",
    slug: "adventurekids",
    logo: "https://example.com/logos/adventurekids.png",
  },
  {
    name: "MusicFun",
    slug: "musicfun",
    logo: "https://example.com/logos/musicfun.png",
  },
  {
    name: "Bandai Namco",
    slug: "bandai-namco",
    logo: "https://example.com/logos/bandai-namco.png",
  },
  {
    name: "LEGO",
    slug: "lego",
    logo: "https://example.com/logos/lego.png",
  },
];
